### ISSUE TITLE
Please add coff/bin file

### ISSUE THREAD

**Issue by djipi** [BitJag/atari_jaguar_240p_test_suite#10]
Please add a link to the coff/bin, or add the file itself.
Building your application outside the atari mint environment leads to missing headers and object files.

**Comment by BitJag** [comment]
I'm purposely avoiding uploading a build bin/cof/rom for the github until we get to a version 1.0 for an official release.
You can download a current version of the code in ROM format from https://jagcorner.com/240p-test-suite/, or build the application yourself if you want access to a bin/cof file.

As for the missing headers and object files, I purposely removed the object files after creating the most recent build that you can download from JagCorner.  As for the headers, these are most likely the headers found in jlibc and rmvlib (the removers library), and requires the atari mint cross compiler to build those, and you will need the latest version of the removers library to build).

Please read the readme and follow links to learn how to setup an appropriate environment for building the application.  I'm very familiar with this setup for debian based linux distributions, and I'm willing to answer questions to help if you run into issues here. If you are trying to setup in windows, you will be a bit more on your own.  I did create a script and tutorial for a similar development environment using cygwin in windows a while ago, but I haven't tested that script in a while.  It would be a good place to start if you have some familiarity with this stuff. https://github.com/BitJag/windows-cygwin-rmvlib-install-scripts

Now that my intentions are clear, I'm worried I might be missing something that could be helpful to this project by providing access to object files and the bin/cof versions of the program.  Is there a specific reason why we would want the bin/cof files and object files, outside of just convenience?

**Comment by djipi** [comment]
Thank you for your feedbacks, and for your work too. I follow it time to time on your Youtube's channel.
I think it is possible to create a pre-Release and add the application but such decision is your of course. The bin/cof/rom build would be for convenience.
I do not think object files could be useful.

I'm on Windows and my toolchain is based on vasm, vlink and gcc (all in ELF format). And I wish to avoid to do modifications in the makefile. I will look at your cygwin script.
